### ISSUE TITLE
search services jdk heap memory size setting

### ISSUE THREAD

**Issue by maxodoble** [Alfresco/alfresco-dockerfiles-bakery#163]
hi,

i can't seem to get the jvm memory size for solr6 (shown in the solr admin gui on bottom of the page) set higher than 1g (obv. the default).

solr_mem_limit for the container is set to 16GB
jvm memory is shown (solr gui - bottom) as 1GB

and i want to increase the jvm memory to 4 or 8 GB for testing a complete reindex.

my compose service for solr6:
```
solr6:
    image: docker.io/alfresco/alfresco-search-services:2.0.15
    mem_limit: "{{ solr_mem_limit }}"
    container_name: {{ app_name }}_solr6
    restart: unless-stopped
    environment:
      SOLR_JAVA_MEM: "-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      SOLR_DATA_DIR_ROOT: "/opt/alfresco-search-services/data"
      SOLR_SOLR_MODEL_DIR: "/opt/alfresco-search-services/data/alfrescoModel"
      # Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      # Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      # Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      # HTTPS or SECRET
      ALFRESCO_SECURE_COMMS: "secret"
      # SHARED SECRET VALUE
      JAVA_TOOL_OPTIONS: >-
        -Dalfresco.secureComms.secret={{ solr_shared_secret }}
    volumes:
      - type: bind
        source: "{{ data_home }}/solr-data"
        target: "/opt/alfresco-search-services/data"
      - solr-keystores:/opt/alfresco-search-services/keystores
      - solr-home:/opt/alfresco-search-services/solrhome
    ports:
      - 127.0.0.1:{{ solr_host_port }}:8983 #Browser port
    networks:
      alfresco:
```

i tried these settings too: 

```
... environment:
#      SOLR_JAVA_MEM: "-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      SOLR_HEAPSIZE: "8g"
```

tried with SOLR_JAVA_MEM (taken from angel borroys docker installer), and without, tried adding SOLR_HEAPSIZE from the README for search services inside this repo:

neither setting seems to increase the heap setting:
* the physical memory on top of solr gui is showing correctly the 16GB.
* the jvm memory always shows size of 1GB

so: what are the correct settings here for increasing the jvm memory?

Thanks,
Max
